#### general settings
name: Citeseer_DE_GAT
train_type: gnnciteseer
gpu_ids: '0'

#### datasets
datasets:
  name: "citeseer"
  dataset_path: "/tmp/Citeseer/raw"

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/GAT_Citeseer"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.001
  weight_decay: 0.0005

#### GNN settings
GNN:
  name: "GAT"
  num_layers: 1
  in_dim: 3703
  hidden_dim: 256
  out_dim: 6
  attn_drop: 0.1
  feat_drop: 0.1
  num_heads: 8
  num_out_heads: 1
  negative_slope: 0.1
  linear: false
  nec: 3

#### Different methods' settings
drop_node:
  use_drop_node: false
  drop_probability: 0.5

drop_edge:
  use_drop_edge: true
  drop_probability: 0.5

random_walk_pe:
  use_random_walk_pe: false
  random_walk_steps: 4

laplacian_pe:
  use_laplacian_pe: false
  laplacian_pe_k: 3
  concatenate_features: true

cga:
  use_cga: false

#### training settings
train:
  num_epochs: 800
  batch_size: 32

logging:
  mode: online
  tags: [
      "Dataset25",
      "Citeseer",
      "GAT",
      "CGA",
#      "RW",
#      "Baseline",
    ]
