#### general settings
name: Aug_GAT_MIMIC3_READM
train_type: gnn
gpu_ids: '0'
task: "readm"

#### datasets
datasets:
  name: "MIMIC3"
  dataset_path: "./data/mimic3_objects/mimic3_dp.pkl"
  graph_path: "./data/graphs/mimic3_dp.pkl"
  labels_path: "./data/graphs/mimic3_dp_labels.pkl"
  entity_mapping: "./data/graphs/mimic3_dp_entity_mapping.pkl"
  edge_dict_path: "./data/graphs/mimic3_dp_edge_dict.pkl"

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/GAT_MIMIC3_READM"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005 # Learning rate
  weight_decay: 0

#### GNN settings
GNN:
  name: "GAT"
  num_layers: 1
  in_dim: 128
  hidden_dim: 128
  out_dim: 351
  attn_drop: 0.15
  feat_drop: 0.15
  num_heads: 8
  num_out_heads: 2
  negative_slope: 0.1
  linear: False
  num_concepts: 50

#### training settings: learning rate scheme, loss, optimizer
train:
  num_epochs: 600
  batch_size: 4096
  temperature: 0.001

logging:
  mode: online
  tags: [
      "MIMIC3",
      "GAT",
      "readm",
      "DS-level",
#      "Baseline",
#      "atten_score",
      "concept",
#      "visualization"
    ]