#### general settings
name: CORA_CGA_GAT_h1
train_type: gnncora
gpu_ids: '0'

#### datasets
datasets:
  name: "cora"
  dataset_path: "/tmp/Cora/raw"

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/GAT_CORA"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.001
  weight_decay: 0.001

#### GNN settings
GNN:
  name: "GAT"
  num_layers: 2
  in_dim: 1433
  hidden_dim: 256
  out_dim: 7
  attn_drop: 0.4
  feat_drop: 0.4
  num_heads: 2
  num_out_heads: 4
  negative_slope: 0.1
  linear: false
  nec: 3

#### Different methods' settings
drop_node:
  use_drop_node: false
  drop_probability: 0.5

drop_edge:
  use_drop_edge: false
  drop_probability: 0.5

random_walk_pe:
  use_random_walk_pe: false
  random_walk_steps: 4

laplacian_pe:
  use_laplacian_pe: false
  laplacian_pe_k: 3
  concatenate_features: true

cga:
  use_cga: true

#### training settings
train:
  num_epochs: 1000
  batch_size: 32

logging:
  mode: online
  tags: [
      "CGA",
#      "Baseline",
      "GAT",
      "CORA"
    ]
