#### general settings
name: Base_GCN_Citeseer
train_type: gnnciteseer
gpu_ids: '0'

#### datasets
datasets:
  name: "citeseer"
  dataset_path: "/tmp/Citeseer/raw"

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/GCN_Citeseer"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.0005
  weight_decay: 0.001

#### GNN settings
GNN:
  name: "GCN"
  num_layers: 2
  in_dim: 3703
  hidden_dim: 8
  out_dim: 6
  feat_drop: 0.01
  nec: 100

#### Different methods' settings
drop_node:
  use_drop_node: false
  drop_probability: 0.5

drop_edge:
  use_drop_edge: false
  drop_probability: 0.5

random_walk_pe:
  use_random_walk_pe: false
  random_walk_steps: 16

laplacian_pe:
  use_laplacian_pe: false
  laplacian_pe_k: 3
  concatenate_features: true

cga:
  use_cga: true

#### training settings
train:
  num_epochs: 600
  batch_size: 32
  temperature: 0.001

logging:
  mode: online
  tags: [
      "Citeseer",
      "GCN",
#      "Baseline",
#      "temp_anneal"
    ]
