#### general settings
name: GCN_OGB_Arxiv_DN
train_type: gnnogb
gpu_ids: '3'
#### Different methods' settings
drop_node:
  use_drop_node: true
  drop_probability: 0.5

drop_edge:
  use_drop_edge: false
  drop_probability: 0.5

random_walk_pe:
  use_random_walk_pe: false
  random_walk_steps: 4

laplacian_pe:
  use_laplacian_pe: false
  laplacian_pe_k: 3
  concatenate_features: true

cga:
  use_cga: false

#### datasets
datasets:
  dataset_path: "/tmp/OGB/raw"

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/GCN_OGB"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.001
  weight_decay: 0.001

#### GNN settings
GNN:
  name: "GCN"
  num_layers: 3
  in_dim: 128
  hidden_dim: 256
  out_dim: 5
  feat_drop: 0.5

#### training settings
train:
  num_epochs: 1000
  batch_size: 4906
  temperature: 0.001

logging:
  mode: online
  tags: [
      "OGB",
      "GCN",
#      "Baseline",
      "temp_anneal"
    ]
