#### general settings
name: Actor_DN_GIN
train_type: gnnactor
gpu_ids: '0'

#### Different methods' settings
drop_node:
  use_drop_node: true
  drop_probability: 0.5

drop_edge:
  use_drop_edge: false
  drop_probability: 0.5

random_walk_pe:
  use_random_walk_pe: false
  random_walk_steps: 4

laplacian_pe:
  use_laplacian_pe: false
  laplacian_pe_k: 3
  concatenate_features: true

cga:
  use_cga: false

#### datasets
datasets:
  name: "actor"
  dataset_path: "/tmp/Actor/raw"

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/GIN_Actor"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005
  weight_decay: 0.0001

#### GNN settings
GNN:
  name: "GIN"
  num_layers: 1
  num_mlp_layers: 2
  in_dim: 932
  hidden_dim: 128
  out_dim: 5
  feat_drop: 0.1
  nec: 1

  neighbor_pooling_type: mean

#### training settings
train:
  num_epochs: 800
  batch_size: 32

logging:
  mode: online
  tags: [
      "Dataset25",
      "Actor",
      "GIN",
#      "DN",
      "Baseline",
    ]
