#### general settings
name: CORA_LP_GIN
train_type: gnncora
gpu_ids: '0'

#### datasets
datasets:
  name: "cora"
  dataset_path: "/tmp/Actor/raw"

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/GIN_CORA"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.0001
  weight_decay: 0.0001

#### GNN settings
GNN:
  name: "GIN"
  num_layers: 2
  num_mlp_layers: 2
  in_dim: 1433
  hidden_dim: 256
  out_dim: 7
  feat_drop: 0.1
  linear: False
  nec: 1

  neighbor_pooling_type: mean

#### Different methods' settings
drop_node:
  use_drop_node: false
  drop_probability: 0.5

drop_edge:
  use_drop_edge: false
  drop_probability: 0.5

random_walk_pe:
  use_random_walk_pe: false
  random_walk_steps: 4

laplacian_pe:
  use_laplacian_pe: true
  laplacian_pe_k: 3
  concatenate_features: true

cga:
  use_cga: false

#### training settings
train:
  num_epochs: 1000
  batch_size: 32

logging:
  mode: online
  tags: [
      "Dataset25",
      "Cora",
      "GIN",
#      "DN",
      "Baseline",
    ]
