#### general settings
name: Citeseer_LP_SAGE
train_type: gnnciteseer
gpu_ids: '0'

#### datasets
datasets:
  name: "citeseer"
  dataset_path: "/tmp/Citeseer/raw"

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/GraphSAGE_Citeseer"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.0001
  weight_decay: 0.0001

#### GNN settings
GNN:
  name: "GraphSAGE"
  num_layers: 2
  in_dim: 3703
  hidden_dim: 128
  out_dim: 6
  feat_drop: 0.2
  linear: false
  nec: 3

#### Different methods' settings
drop_node:
  use_drop_node: false
  drop_probability: 0.5

drop_edge:
  use_drop_edge: false
  drop_probability: 0.5

random_walk_pe:
  use_random_walk_pe: false
  random_walk_steps: 4

laplacian_pe:
  use_laplacian_pe: true
  laplacian_pe_k: 3
  concatenate_features: true

cga:
  use_cga: false


#### training settings
train:
  num_epochs: 600
  batch_size: 32

logging:
  mode: online
  tags: [
      "Dataset25",
      "Citeseer",
      "GraphSAGE",
      "CGA",
#      "RW",
#      "Baseline",
    ]
