#### general settings
name: SAGE_OGB_Arxiv_CGA
train_type: gnnogb
gpu_ids: '0'

#### Different methods' settings
drop_node:
  use_drop_node: false
  drop_probability: 0.5

drop_edge:
  use_drop_edge: false
  drop_probability: 0.5

random_walk_pe:
  use_random_walk_pe: false
  random_walk_steps: 4

laplacian_pe:
  use_laplacian_pe: true
  laplacian_pe_k: 3
  concatenate_features: true

cga:
  use_cga: false

#### datasets
datasets:
  name: "ogb"
  dataset_path: "/tmp/OGB/raw"

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/GraphSAGE_OGB"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.0001
  weight_decay: 0.0001

#### GNN settings
GNN:
  name: "GraphSAGE"
  num_layers: 2
  in_dim: 932
  hidden_dim: 128
  out_dim: 5
  feat_drop: 0.2
  nec: 100


#### training settings
train:
  num_epochs: 1000
  batch_size: 32

logging:
  mode: online
  tags: [
      "Dataset45",
      "OGB",
      "GraphSAGE",
#      "DN",
      "Baseline",
    ]
