#### general settings
name: CORA_RW_SAGE
train_type: gnncora
gpu_ids: '0'

#### Different methods' settings
drop_node:
  use_drop_node: false
  drop_probability: 0.5

drop_edge:
  use_drop_edge: false
  drop_probability: 0.5

random_walk_pe:
  use_random_walk_pe: true
  random_walk_steps: 4

laplacian_pe:
  use_laplacian_pe: false
  laplacian_pe_k: 3
  concatenate_features: true

cga:
  use_cga: false

#### datasets
datasets:
  name: "cora"
  dataset_path: "/tmp/Cora/raw"

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/GraphSAGE_CORA"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.0001
  weight_decay: 0.0001

#### GNN settings
GNN:
  name: "GraphSAGE"
  num_layers: 2
  in_dim: 1433
  hidden_dim: 256
  out_dim: 7
  feat_drop: 0.2
  nec: 3


#### training settings
train:
  num_epochs: 500
  batch_size: 32

logging:
  mode: online
  tags: [
      "Dataset25",
      "CORA",
      "GraphSAGE",
#      "DN",
#      "Baseline",
      "CGA",
    ]
